import 'package:flutter/material.dart';
import 'package:fms/controller/model/feed_useage_model.dart';

class FeedUsageReport extends StatefulWidget {
  const FeedUsageReport({super.key});

  @override
  State<FeedUsageReport> createState() => _FeedUsageReportState();
}

class _FeedUsageReportState extends State<FeedUsageReport> {
 final List<FeedUsageReportModel> reports = [
    FeedUsageReportModel(
      livestockId: 'Livestock-001',
      feedType: 'Hay',
      feedQuantity: 10.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '7 days',
      feedCost: 50.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Livestock seemed to enjoy the hay.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-002',
      feedType: 'Grain',
      feedQuantity: 5.0,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 30.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Livestock showed good appetite with the grain.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-003',
      feedType: 'Silage',
      feedQuantity: 15.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '30 days',
      feedCost: 80.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Silage quality was excellent.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-004',
      feedType: 'Pellets',
      feedQuantity: 8.0,
      feedFrequency: 'Three times a day',
      feedingDuration: '10 days',
      feedCost: 45.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Livestock easily consumed the pellets.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-005',
      feedType: 'Hay',
      feedQuantity: 12.0,
      feedFrequency: 'Once a day',
      feedingDuration: '7 days',
      feedCost: 55.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Hay quality was satisfactory.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-006',
      feedType: 'Grain',
      feedQuantity: 6.5,
      feedFrequency: 'Twice a day',
      feedingDuration: '21 days',
      feedCost: 40.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Livestock gradually adapted to the grain diet.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-007',
      feedType: 'Silage',
      feedQuantity: 20.0,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 90.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Silage was well-received by the livestock.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-008',
      feedType: 'Pellets',
      feedQuantity: 7.5,
      feedFrequency: 'Three times a day',
      feedingDuration: '7 days',
      feedCost: 50.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Pellets improved the livestock'
    ),
      FeedUsageReportModel(
      livestockId: 'Livestock-001',
      feedType: 'Hay',
      feedQuantity: 10.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '7 days',
      feedCost: 50.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Livestock seemed to enjoy the hay.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-002',
      feedType: 'Grain',
      feedQuantity: 5.0,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 30.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Livestock showed good appetite with the grain.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-003',
      feedType: 'Silage',
      feedQuantity: 15.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '30 days',
      feedCost: 80.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Silage quality was excellent.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-004',
      feedType: 'Pellets',
      feedQuantity: 8.0,
      feedFrequency: 'Three times a day',
      feedingDuration: '10 days',
      feedCost: 45.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Livestock easily consumed the pellets.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-005',
      feedType: 'Hay',
      feedQuantity: 12.0,
      feedFrequency: 'Once a day',
      feedingDuration: '7 days',
      feedCost: 55.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Hay quality was satisfactory.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-006',
      feedType: 'Grain',
      feedQuantity: 6.5,
      feedFrequency: 'Twice a day',
      feedingDuration: '21 days',
      feedCost: 40.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Livestock gradually adapted to the grain diet.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-007',
      feedType: 'Silage',
      feedQuantity: 20.0,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 90.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Silage was well-received by the livestock.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-008',
      feedType: 'Pellets',
      feedQuantity: 7.5,
      feedFrequency: 'Three times a day',
      feedingDuration: '7 days',
      feedCost: 50.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Pellets improved the livestock\'s weight gain.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-009',
      feedType: 'Hay',
      feedQuantity: 11.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '10 days',
      feedCost: 60.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Livestock enjoyed the fresh hay.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-010',
      feedType: 'Grain',
      feedQuantity: 5.0,
      feedFrequency: 'Once a day',
      feedingDuration: '7 days',
      feedCost: 35.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Grain intake was moderate.',
    ),
        FeedUsageReportModel(
      livestockId: 'Livestock-011',
      feedType: 'Hay',
      feedQuantity: 8.0,
      feedFrequency: 'Once a day',
      feedingDuration: '10 days',
      feedCost: 45.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Livestock enjoyed the fresh hay.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-012',
      feedType: 'Grain',
      feedQuantity: 6.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '21 days',
      feedCost: 40.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Gradual transition to grain diet.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-013',
      feedType: 'Silage',
      feedQuantity: 18.0,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 80.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Silage intake was consistent.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-014',
      feedType: 'Pellets',
      feedQuantity: 9.0,
      feedFrequency: 'Three times a day',
      feedingDuration: '7 days',
      feedCost: 55.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Pellets helped maintain good weight.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-015',
      feedType: 'Hay',
      feedQuantity: 11.5,
      feedFrequency: 'Twice a day',
      feedingDuration: '7 days',
      feedCost: 50.0,
      feedSource: 'Farmers Cooperative',
      feedingNotes: 'Livestock enjoyed the high-quality hay.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-016',
      feedType: 'Grain',
      feedQuantity: 5.5,
      feedFrequency: 'Once a day',
      feedingDuration: '14 days',
      feedCost: 35.0,
      feedSource: 'XYZ Feed Store',
      feedingNotes: 'Moderate grain intake observed.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-017',
      feedType: 'Silage',
      feedQuantity: 22.0,
      feedFrequency: 'Twice a day',
      feedingDuration: '30 days',
      feedCost: 90.0,
      feedSource: 'Green Pastures Feed Mill',
      feedingNotes: 'Silage provided good nutrition.',
    ),
    FeedUsageReportModel(
      livestockId: 'Livestock-018',
      feedType: 'Pellets',
      feedQuantity: 8.5,
      feedFrequency: 'Three times a day',
      feedingDuration: '10 days',
      feedCost: 60.0,
      feedSource: 'ABC Farm Supply',
      feedingNotes: 'Pellets contributed to weight gain.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:const  Text("Feed usage Reports"),
        centerTitle: true,
      ),
      body:  SingleChildScrollView(
        child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: DataTable(
                columns:const [
                   DataColumn(label: Text('#')),
                  DataColumn(label: Text('Livestock ID')),
                  DataColumn(label: Text('Feed Type')),
                  DataColumn(label: Text('Feed Quantity')),
                  DataColumn(label: Text('Feed Frequency')),
                  DataColumn(label: Text('Feeding Duration')),
                  DataColumn(label: Text('Feed Cost')),
                  DataColumn(label: Text('Feed Source')),
                  DataColumn(label: Text('Feeding Notes')),
                  DataColumn(label: Text('Action')),
                ],
                rows: reports.map((report) {
                  int count=1;
                  return DataRow(cells: [
                    DataCell(Text(count.toString())),
                    DataCell(Text(report.livestockId)),
                    DataCell(Text(report.feedType)),
                    DataCell(Text(report.feedQuantity.toString())),
                    DataCell(Text(report.feedFrequency)),
                    DataCell(Text(report.feedingDuration)),
                    DataCell(Text(report.feedCost.toString())),
                    DataCell(Text(report.feedSource)),
                    DataCell(Text(report.feedingNotes)),
                      DataCell(Row(children: [
                          IconButton(onPressed: (){}, icon: const Icon(Icons.edit, color: Colors.green, size: 25,)
                          ),
                          IconButton(onPressed: (){}, icon: const Icon(Icons.remove_red_eye_outlined, color: Colors.grey, size: 30,)
                          ),
                          IconButton(onPressed: (){}, icon: const Icon(Icons.delete, color: Colors.red, size: 25,)
                          ),
                        ],)),
                  ]);
                  
                }).toList(),
              ),
            ),
          ),
      ),
        floatingActionButton: FloatingActionButton(onPressed: (){}, child: const Icon(Icons.add),),
    );
  }
}