// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwb_BF3HXTyiKoZh8FfEYNN_DlKd7_3jw',
    appId: '1:972089465483:web:aa0b4b41f861a7fe2ed28e',
    messagingSenderId: '972089465483',
    projectId: 'farm-management-system-548dc',
    authDomain: 'farm-management-system-548dc.firebaseapp.com',
    storageBucket: 'farm-management-system-548dc.appspot.com',
    measurementId: 'G-VQR3KCWZV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANSDz6JQau_J-jRkOg2qjuzSG1AJzv5qQ',
    appId: '1:972089465483:android:3e4fdc855e194e2e2ed28e',
    messagingSenderId: '972089465483',
    projectId: 'farm-management-system-548dc',
    storageBucket: 'farm-management-system-548dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlh-B85vCvqbKA665ERPlkQMoI_mXhePY',
    appId: '1:972089465483:ios:85566d4617322b422ed28e',
    messagingSenderId: '972089465483',
    projectId: 'farm-management-system-548dc',
    storageBucket: 'farm-management-system-548dc.appspot.com',
    iosClientId: '972089465483-j5apckllp5nhem0imkcvq33ib1n4494b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlh-B85vCvqbKA665ERPlkQMoI_mXhePY',
    appId: '1:972089465483:ios:85566d4617322b422ed28e',
    messagingSenderId: '972089465483',
    projectId: 'farm-management-system-548dc',
    storageBucket: 'farm-management-system-548dc.appspot.com',
    iosClientId: '972089465483-j5apckllp5nhem0imkcvq33ib1n4494b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fms',
  );
}
